INSERT INTO dwh_uiaf.dimactividadeconimica (idactividadeconomica,actividadeconomica,codigoactividad)
values (1,'No aplica','Noap'),
(2,'No homologado','Noho'),
(3,'No reporta','Nore'),
(4,'Error en la fuente','Eren'),
(10,'Agricultura, ganadería, caza y actividades de servicios conexas ','0001'),
(11,'Cultivos agrícolas transitorios ','011'),
(12,'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas ','0111'),
(13,'Cultivo de arroz ','0112'),
(14,'Cultivo de hortalizas, raíces y tubérculos ','0113'),
(15,'Cultivo de tabaco ','0114'),
(16,'Cultivo de plantas textiles ','0115'),
(17,'Otros cultivos transitorios n.c.p.','0119'),
(18,'Cultivos agrícolas permanentes ','012'),
(19,'Cultivo de frutas tropicales y subtropicales','0121'),
(20,'Cultivo de plátano y banano','0122'),
(21,'Cultivo de café','0123'),
(22,'Cultivo de caña de azúcar','0124'),
(23,'Cultivo de flor de corte','0125'),
(24,'Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos','0126'),
(25,'Cultivo de plantas con las que se preparan bebidas','0127'),
(26,'Cultivo de especias y de plantas aromáticas y medicinales ','0128'),
(27,'Otros cultivos permanentes n.c.p.','0129'),
(28,'Propagación de plantas (actividades de los viveros, excepto viveros forestales) ','0130'),
(29,'Ganadería ','014'),
(30,'Cría de ganado bovino y bufalino','0141'),
(31,'Cría de caballos y otros equinos ','0142'),
(32,'Cría de ovejas y cabras ','0143'),
(33,'Cría de ganado porcino','0144'),
(34,'Cría de aves de corral','0145'),
(35,'Cría de otros animales n.c.p.','0149'),
(36,'Explotación mixta (agrícola y pecuaria) ','0150'),
(37,'Actividades de apoyo a la agricultura y la ganadería, y actividades posteriores a la cosecha ','016'),
(38,'Actividades de apoyo a la agricultura ','0161'),
(39,'Actividades de apoyo a la ganadería','0162'),
(40,'Actividades posteriores a la cosecha ','0163'),
(41,'Tratamiento de semillas para propagación ','0164'),
(42,'Caza ordinaria y mediante trampas y actividades de servicios conexas ','0170'),
(43,'Silvicultura y extracción de madera','0002'),
(44,'Silvicultura y otras actividades forestales','0210'),
(45,'Extracción de madera ','0220'),
(46,'Recolección de productos forestales diferentes a la madera','0230'),
(47,'Servicios de apoyo a la silvicultura ','0240'),
(48,'Pesca y acuicultura','0003'),
(49,'Pesca ','031'),
(50,'Pesca marítima ','0311'),
(51,'Pesca de agua dulce ','0312'),
(52,'Acuicultura ','032'),
(53,'Acuicultura marítima ','0321'),
(54,'Acuicultura de agua dulce','0322'),
(55,'Extracción de carbón de piedra y lignito','0005'),
(56,'Extracción de hulla (carbón de piedra)','0510'),
(57,'Extracción de carbón lignito','0520'),
(58,'Extracción de petróleo crudo y gas natural','0006'),
(59,'Extracción de petróleo crudo','0610'),
(60,'Extracción de gas natural','0620'),
(61,'Extracción de minerales metalíferos','0007'),
(62,'Extracción de minerales de hierro','0710'),
(63,'Extracción de minerales metalíferos no ferrosos','072'),
(64,'Extracción de minerales de uranio y de torio','0721'),
(65,'Extracción de oro y otros metales preciosos','0722'),
(66,'Extracción de minerales de níquel','0723'),
(67,'Extracción de otros minerales metalíferos no ferrosos n.c.p.','0729'),
(68,'Extracción de otras minas y canteras','0008'),
(69,'Extracción de piedra, arena, arcillas, cal, yeso, caolín, bentonitas y similares','081'),
(70,'Extracción de piedra, arena, arcillas comunes, yeso y anhidrita','0811'),
(71,'Extracción de arcillas de uso industrial, caliza, caolín y bentonitas','0812'),
(72,'Extracción de esmeraldas, piedras preciosas y semipreciosas','0820'),
(73,'Extracción de otros minerales no metálicos n.c.p.','089'),
(74,'Extracción de minerales para la fabricación de abonos y productos químicos','0891'),
(75,'Extracción de halita (sal)','0892'),
(76,'Extracción de otros minerales no metálicos n.c.p.','0899'),
(77,'Actividades de servicios de apoyo para la explotación de minas ','0009'),
(78,'Actividades de apoyo para la extracción de petróleo y de gas natural','0910'),
(79,'Actividades de apoyo para otras actividades de explotación de minas y canteras','0990'),
(80,'Elaboración de productos alimenticios','0010'),
(81,'Procesamiento y conservación de carne, pescado, crustáceos y moluscos ','101'),
(82,'Procesamiento y conservación de carne y productos cárnicos','1011'),
(83,'Procesamiento y conservación de pescados, crustáceos y moluscos','1012'),
(84,'Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos','1020'),
(85,'Elaboración de aceites y grasas de origen vegetal y animal','1030'),
(86,'Elaboración de productos lácteos','1040'),
(87,'Elaboración de productos de molinería, almidones y productos derivados del almidón','105'),
(88,'Elaboración de productos de molinería','1051'),
(89,'Elaboración de almidones y productos derivados del almidón','1052'),
(90,'Elaboración de productos de café','106'),
(91,'Trilla de café','1061'),
(92,'Descafeinado, tostión y molienda del café','1062'),
(93,'Otros derivados del café','1063'),
(94,'Elaboración de azúcar y panela','107'),
(95,'Elaboración y refinación de azúcar','1071'),
(96,'Elaboración de panela','1072'),
(97,'Elaboración de otros productos alimenticios','108'),
(98,'Elaboración de productos de panadería','1081'),
(99,'Elaboración de cacao, chocolate y productos de confitería','1082'),
(100,'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares','1083'),
(101,'Elaboración de comidas y platos preparados','1084'),
(102,'Elaboración de otros productos alimenticios n.c.p.','1089'),
(103,'Elaboración de alimentos preparados para animales','1090'),
(104,'Elaboración de bebidas','0011'),
(105,'Elaboración de bebidas','110'),
(106,'Destilación, rectificación y mezcla de bebidas alcohólicas','1101'),
(107,'Elaboración de bebidas fermentadas no destiladas','1102'),
(108,'Producción de malta, elaboración de cervezas y otras bebidas malteadas','1103'),
(109,'Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas','1104'),
(110,'Elaboración de productos de tabaco','0012'),
(111,'Elaboración de productos de tabaco','1200'),
(112,'Fabricación de productos textiles','0013'),
(113,'Preparación, hilatura, tejeduría y acabado de productos textiles','131'),
(114,'Preparación e hilatura de fibras textiles','1311'),
(115,'Tejeduría de productos textiles','1312'),
(116,'Acabado de productos textiles','1313'),
(117,'Fabricación de otros productos textiles','139'),
(118,'Fabricación de tejidos de punto y ganchillo','1391'),
(119,'Confección de artículos con materiales textiles, excepto prendas de vestir','1392'),
(120,'Fabricación de tapetes y alfombras para pisos','1393'),
(121,'Fabricación de cuerdas, cordeles, cables, bramantes y redes','1394'),
(122,'Fabricación de otros artículos textiles n.c.p.','1399'),
(123,'Confección de prendas de vestir','0014'),
(124,'Confección de prendas de vestir, excepto prendas de piel','1410'),
(125,'Fabricación de artículos de piel','1420'),
(126,'Fabricación de artículos de punto y ganchillo','1430'),
(127,'Curtido y recurtido de cueros; fabricación de calzado; fabricación de artículos de viaje, maletas, bolsos de mano y artículos similares, y fabricación de artículos de talabartería y guarnicionería; adobo y teñido de pieles','0015'),
(128,'Curtido y recurtido de cueros; fabricación de artículos de viaje, bolsos de mano y artículos similares, y fabricación de artículos de talabartería y guarnicionería, adobo y teñido de pieles','151'),
(129,'Curtido y recurtido de cueros; recurtido y teñido de pieles','1511'),
(130,'Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería','1512'),
(131,'Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales','1513'),
(132,'Fabricación de calzado','152'),
(133,'Fabricación de calzado de cuero y piel, con cualquier tipo de suela','1521'),
(134,'Fabricación de otros tipos de calzado, excepto calzado de cuero y piel','1522'),
(135,'Fabricación de partes del calzado','1523'),
(136,'Transformación de la madera y fabricación de productos de madera y de corcho, excepto muebles; fabricación de artículos de cestería y espartería','0016'),
(137,'Aserrado, acepillado e impregnación de la madera','1610'),
(138,'Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles','1620'),
(139,'Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción','1630'),
(140,'Fabricación de recipientes de madera','1640'),
(141,'Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería','1690'),
(142,'Fabricación de papel, cartón y productos de papel y cartón','0017'),
(143,'Fabricación de papel, cartón y productos de papel y cartón','170'),
(144,'Fabricación de pulpas (pastas) celulósicas; papel y cartón','1701'),
(145,'Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón.','1702'),
(146,'Fabricación de otros artículos de papel y cartón','1709'),
(147,'Actividades de impresión y de producción de copias a partir de grabaciones originales ','0018'),
(148,'Actividades de impresión y actividades de servicios relacionados con la impresión','181'),
(149,'Actividades de impresión','1811'),
(150,'Actividades de servicios relacionados con la impresión','1812'),
(151,'Producción de copias a partir de grabaciones originales ','1820'),
(152,'Coquización, fabricación de productos de la refinación del petróleo y actividad de mezcla de combustibles ','0019'),
(153,'Fabricación de productos de hornos de coque','1910'),
(154,'Fabricación de productos de la refinación del petróleo','192'),
(155,'Fabricación de productos de la refinación del petróleo','1921'),
(156,'Actividad de mezcla de combustibles','1922'),
(157,'Fabricación de sustancias y productos químicos','0020'),
(158,'Fabricación de sustancias químicas básicas, abonos y compuestos inorgánicos nitrogenados, plásticos y caucho sintético en formas primarias','201'),
(159,'Fabricación de sustancias y productos químicos básicos','2011'),
(160,'Fabricación de abonos y compuestos inorgánicos nitrogenados','2012'),
(161,'Fabricación de plásticos en formas primarias','2013'),
(162,'Fabricación de caucho sintético en formas primarias','2014'),
(163,'Fabricación de otros productos químicos','202'),
(164,'Fabricación de plaguicidas y otros productos químicos de uso agropecuario','2021'),
(165,'Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas','2022'),
(166,'Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador','2023'),
(167,'Fabricación de otros productos químicos n.c.p.','2029'),
(168,'Fabricación de fibras sintéticas y artificiales','2030'),
(169,'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico','0021'),
(170,'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico','2100'),
(171,'Fabricación de productos de caucho y de plástico','0022'),
(172,'Fabricación de productos de caucho','221'),
(173,'Fabricación de llantas y neumáticos de caucho','2211'),
(174,'Reencauche de llantas usadas','2212'),
(175,'Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.','2219'),
(176,'Fabricación de productos de plástico','222'),
(177,'Fabricación de formas básicas de plástico','2221'),
(178,'Fabricación de artículos de plástico n.c.p.','2229'),
(179,'Fabricación de otros productos minerales no metálicos','0023'),
(180,'Fabricación de vidrio y productos de vidrio','2310'),
(181,'Fabricación de productos minerales no metálicos n.c.p.','239'),
(182,'Fabricación de productos refractarios','2391'),
(183,'Fabricación de materiales de arcilla para la construcción','2392'),
(184,'Fabricación de otros productos de cerámica y porcelana','2393'),
(185,'Fabricación de cemento, cal y yeso','2394'),
(186,'Fabricación de artículos de hormigón, cemento y yeso','2395'),
(187,'Corte, tallado y acabado de la piedra','2396'),
(188,'Fabricación de otros productos minerales no metálicos n.c.p.','2399'),
(189,'Fabricación de productos metalúrgicos básicos','0024'),
(190,'Industrias básicas de hierro y de acero','2410'),
(191,'Industrias básicas de metales preciosos y de metales no ferrosos','242'),
(192,'Industrias básicas de metales preciosos','2421'),
(193,'Industrias básicas de otros metales no ferrosos','2429'),
(194,'Fundición de metales','243'),
(195,'Fundición de hierro y de acero','2431'),
(196,'Fundición de metales no ferrosos ','2432'),
(197,'Fabricación de productos elaborados de metal, excepto maquinaria y equipo','0025'),
(198,'Fabricación de productos metálicos para uso estructural, tanques, depósitos y generadores de vapor','251'),
(199,'Fabricación de productos metálicos para uso estructural','2511'),
(200,'Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías','2512'),
(201,'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central','2513'),
(202,'Fabricación de armas y municiones','2520'),
(203,'Fabricación de otros productos elaborados de metal y actividades de servicios relacionadas con el trabajo de metales','259'),
(204,'Forja, prensado, estampado y laminado de metal; pulvimetalurgia','2591'),
(205,'Tratamiento y revestimiento de metales; mecanizado','2592'),
(206,'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería','2593'),
(207,'Fabricación de otros productos elaborados de metal n.c.p.','2599'),
(208,'Fabricación de productos informáticos, electrónicos y ópticos','0026'),
(209,'Fabricación de componentes y tableros electrónicos','2610'),
(210,'Fabricación de computadoras y de equipo periférico','2620'),
(211,'Fabricación de equipos de comunicación','2630'),
(212,'Fabricación de aparatos electrónicos de consumo','2640'),
(213,'Fabricación de equipo de medición, prueba, navegación y control; fabricación de relojes','265'),
(214,'Fabricación de equipo de medición, prueba, navegación y control','2651'),
(215,'Fabricación de relojes','2652'),
(216,'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico','2660'),
(217,'Fabricación de instrumentos ópticos y equipo fotográfico','2670'),
(218,'Fabricación de medios magnéticos y ópticos para almacenamiento de datos','2680'),
(219,'Fabricación de aparatos y equipo eléctrico','0027'),
(220,'Fabricación de motores, generadores y transformadores eléctricos y de aparatos de distribución y control de la energía eléctrica','271'),
(221,'Fabricación de motores, generadores y transformadores eléctricos','2711'),
(222,'Fabricación de aparatos de distribución y control de la energía eléctrica','2712'),
(223,'Fabricación de pilas, baterías y acumuladores eléctricos','2720'),
(224,'Fabricación de hilos y cables aislados y sus dispositivos','273'),
(225,'Fabricación de hilos y cables eléctricos y de fibra óptica','2731'),
(226,'Fabricación de dispositivos de cableado','2732'),
(227,'Fabricación de equipos eléctricos de iluminación','2740'),
(228,'Fabricación de aparatos de uso doméstico','2750'),
(229,'Fabricación de otros tipos de equipo eléctrico n.c.p.','2790'),
(230,'Fabricación de maquinaria y equipo n.c.p.','0028'),
(231,'Fabricación de maquinaria y equipo de uso general','281'),
(232,'Fabricación de motores, turbinas, y partes para motores de combustión interna','2811'),
(233,'Fabricación de equipos de potencia hidráulica y neumática','2812'),
(234,'Fabricación de otras bombas, compresores, grifos y válvulas','2813'),
(235,'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión','2814'),
(236,'Fabricación de hornos, hogares y quemadores industriales','2815'),
(237,'Fabricación de equipo de elevación y manipulación','2816'),
(238,'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)','2817'),
(239,'Fabricación de herramientas manuales con motor','2818'),
(240,'Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.','2819'),
(241,'Fabricación de maquinaria y equipo de uso especial','282'),
(242,'Fabricación de maquinaria agropecuaria y forestal','2821'),
(243,'Fabricación de máquinas formadoras de metal y de máquinas herramienta','2822'),
(244,'Fabricación de maquinaria para la metalurgia','2823'),
(245,'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción','2824'),
(246,'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco','2825'),
(247,'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros','2826'),
(248,'Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.','2829'),
(249,'Fabricación de vehículos automotores, remolques y semirremolques','0029'),
(250,'Fabricación de vehículos automotores y sus motores','2910'),
(251,'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques ','2920'),
(252,'Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores','2930'),
(253,'Fabricación de otros tipos de equipo de transporte','0030'),
(254,'Construcción de barcos y otras embarcaciones','301'),
(255,'Construcción de barcos y de estructuras flotantes','3011'),
(256,'Construcción de embarcaciones de recreo y deporte','3012'),
(257,'Fabricación de locomotoras y de material rodante para ferrocarriles','3020'),
(258,'Fabricación de aeronaves, naves espaciales y de maquinaria conexa','3030'),
(259,'Fabricación de vehículos militares de combate','3040'),
(260,'Fabricación de otros tipos de equipo de transporte n.c.p.','309'),
(261,'Fabricación de motocicletas','3091'),
(262,'Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad','3092'),
(263,'Fabricación de otros tipos de equipo de transporte n.c.p.','3099'),
(264,'Fabricación de muebles, colchones y somieres','0031'),
(265,'Fabricación de muebles ','3110'),
(266,'Fabricación de colchones y somieres','3120'),
(267,'Otras industrias manufactureras','0032'),
(268,'Fabricación de joyas, bisutería y artículos conexos','3210'),
(269,'Fabricación de instrumentos musicales','3220'),
(270,'Fabricación de artículos y equipo para la práctica del deporte','3230'),
(271,'Fabricación de juegos, juguetes y rompecabezas','3240'),
(272,'Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)','3250'),
(273,'Otras industrias manufactureras n.c.p.','3290'),
(274,'Instalación, mantenimiento y reparación especializado de maquinaria y equipo','0033'),
(275,'Mantenimiento y reparación especializado de productos elaborados en metal y de maquinaria y equipo','331'),
(276,'Mantenimiento y reparación especializado de productos elaborados en metal','3311'),
(277,'Mantenimiento y reparación especializado de maquinaria y equipo','3312'),
(278,'Mantenimiento y reparación especializado de equipo electrónico y óptico','3313'),
(279,'Mantenimiento y reparación especializado de equipo eléctrico','3314'),
(280,'Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas','3315'),
(281,'Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.','3319'),
(282,'Instalación especializada de maquinaria y equipo industrial ','3320'),
(283,'Suministro de electricidad, gas, vapor y aire acondicionado ','0035'),
(284,'Generación, transmisión, distribución y comercialización de energía eléctrica','351'),
(285,'Generación de energía eléctrica','3511'),
(286,'Transmisión de energía eléctrica','3512'),
(287,'Distribución de energía eléctrica','3513'),
(288,'Comercialización de energía eléctrica','3514'),
(289,'Producción de gas; distribución de combustibles gaseosos por tuberías','3520'),
(290,'Suministro de vapor y aire acondicionado','3530'),
(291,'Captación, tratamiento y distribución de agua','0036'),
(292,'Captación, tratamiento y distribución de agua','3600'),
(293,'Evacuación y tratamiento de aguas residuales','0037'),
(294,'Evacuación y tratamiento de aguas residuales','3700'),
(295,'Recolección, tratamiento y disposición de desechos, recuperación de materiales','0038'),
(296,'Recolección de desechos','381'),
(297,'Recolección de desechos no peligrosos','3811'),
(298,'Recolección de desechos peligrosos','3812'),
(299,'Tratamiento y disposición de desechos','382'),
(300,'Tratamiento y disposición de desechos no peligrosos','3821'),
(301,'Tratamiento y disposición de desechos peligrosos','3822'),
(302,'Recuperación de materiales','3830'),
(303,'Actividades de saneamiento ambiental y otros servicios de gestión de desechos','0039'),
(304,'Actividades de saneamiento ambiental y otros servicios de gestión de desechos','3900'),
(305,'Construcción de edificios','0041'),
(306,'Construcción de edificios','411'),
(307,'Construcción de edificios residenciales','4111'),
(308,'Construcción de edificios no residenciales','4112'),
(309,'Obras de ingeniería civil','0042'),
(310,'Construcción de carreteras y vías de ferrocarril','4210'),
(311,'Construcción de proyectos de servicio público','4220'),
(312,'Construcción de otras obras de ingeniería civil','4290'),
(313,'Actividades especializadas para la construcción de edificios y obras de ingeniería civil','0043'),
(314,'Demolición y preparación del terreno','431'),
(315,'Demolición','4311'),
(316,'Preparación del terreno','4312'),
(317,'Instalaciones eléctricas, de fontanería y otras instalaciones especializadas','432'),
(318,'Instalaciones eléctricas','4321'),
(319,'Instalaciones de fontanería, calefacción y aire acondicionado','4322'),
(320,'Otras instalaciones especializadas','4329'),
(321,'Terminación y acabado de edificios y obras de ingeniería civil','4330'),
(322,'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil','4390'),
(323,'Comercio, mantenimiento y reparación de vehículos automotores y motocicletas, sus partes, piezas y accesorios','0045'),
(324,'Comercio de vehículos automotores','451'),
(325,'Comercio de vehículos automotores nuevos','4511'),
(326,'Comercio de vehículos automotores usados','4512'),
(327,'Mantenimiento y reparación de vehículos automotores','4520'),
(328,'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores','4530'),
(329,'Comercio, mantenimiento y reparación de motocicletas y de sus partes, piezas y accesorios','454'),
(330,'Comercio de motocicletas y de sus partes, piezas y accesorios','4541'),
(331,'Mantenimiento y reparación de motocicletas y de sus partes y piezas','4542'),
(332,'Comercio al por mayor y en comisión o por contrata, excepto el comercio de vehículos automotores y motocicletas','0046'),
(333,'Comercio al por mayor a cambio de una retribución o por contrata','4610'),
(334,'Comercio al por mayor de materias primas agropecuarias; animales vivos','4620'),
(335,'Comercio al por mayor de alimentos, bebidas y tabaco','463'),
(336,'Comercio al por mayor de productos alimenticios','4631'),
(337,'Comercio al por mayor de bebidas y tabaco','4632'),
(338,'Comercio al por mayor de artículos y enseres domésticos (incluidas prendas de vestir)','464'),
(339,'Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico','4641'),
(340,'Comercio al por mayor de prendas de vestir','4642'),
(341,'Comercio al por mayor de calzado','4643'),
(342,'Comercio al por mayor de aparatos y equipo de uso doméstico','4644'),
(343,'Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador','4645'),
(344,'Comercio al por mayor de otros utensilios domésticos n.c.p.','4649'),
(345,'Comercio al por mayor de maquinaria y equipo ','465'),
(346,'Comercio al por mayor de computadores, equipo periférico y programas de informática','4651'),
(347,'Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones','4652'),
(348,'Comercio al por mayor de maquinaria y equipo agropecuarios','4653'),
(349,'Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.','4659'),
(350,'Comercio al por mayor especializado de otros productos','466'),
(351,'Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos','4661'),
(352,'Comercio al por mayor de metales y productos metalíferos','4662'),
(353,'Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción','4663'),
(354,'Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario','4664'),
(355,'Comercio al por mayor de desperdicios, desechos y chatarra','4665'),
(356,'Comercio al por mayor de otros productos n.c.p.','4669'),
(357,'Comercio al por mayor no especializado','4690'),
(358,'Comercio al por menor (incluso el comercio al por menor de combustibles), excepto el de vehículos automotores y motocicletas','0047'),
(359,'Comercio al por menor en establecimientos no especializados','471'),
(360,'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco','4711'),
(361,'Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco','4719'),
(362,'Comercio al por menor de alimentos (víveres en general), bebidas y tabaco, en establecimientos especializados','472'),
(363,'Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados','4721'),
(364,'Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados','4722'),
(365,'Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados','4723'),
(366,'Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados','4724'),
(367,'Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados','4729'),
(368,'Comercio al por menor de combustible, lubricantes, aditivos y productos de limpieza para automotores, en establecimientos especializados','473'),
(369,'Comercio al por menor de combustible para automotores','4731'),
(370,'Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores','4732'),
(371,'Comercio al por menor de equipos de informática y de comunicaciones, en establecimientos especializados','474'),
(372,'Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados','4741'),
(373,'Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados','4742'),
(374,'Comercio al por menor de otros enseres domésticos en establecimientos especializados','475'),
(375,'Comercio al por menor de productos textiles en establecimientos especializados','4751'),
(376,'Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados','4752'),
(377,'Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados','4753'),
(378,'Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación','4754'),
(379,'Comercio al por menor de artículos y utensilios de uso doméstico','4755'),
(380,'Comercio al por menor de otros artículos domésticos en establecimientos especializados','4759'),
(381,'Comercio al por menor de artículos culturales y de entretenimiento, en establecimientos especializados','476'),
(382,'Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados','4761'),
(383,'Comercio al por menor de artículos deportivos, en establecimientos especializados ','4762'),
(384,'Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados','4769'),
(385,'Comercio al por menor de otros productos en establecimientos especializados','477'),
(386,'Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados','4771'),
(387,'Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.','4772'),
(388,'Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados','4773'),
(389,'Comercio al por menor de otros productos nuevos en establecimientos especializados','4774'),
(390,'Comercio al por menor de artículos de segunda mano','4775'),
(391,'Comercio al por menor en puestos de venta móviles','478'),
(392,'Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles','4781'),
(393,'Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles','4782'),
(394,'Comercio al por menor de otros productos en puestos de venta móviles','4789'),
(395,'Comercio al por menor no realizado en establecimientos, puestos de venta o mercados','479'),
(396,'Comercio al por menor realizado a través de Internet','4791'),
(397,'Comercio al por menor realizado a través de casas de venta o por correo','4792'),
(398,'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados.','4799'),
(399,'Transporte terrestre; transporte por tuberías','0049'),
(400,'Transporte férreo','491'),
(401,'Transporte férreo de pasajeros','4911'),
(402,'Transporte férreo de carga ','4912'),
(403,'Transporte terrestre público automotor','492'),
(404,'Transporte de pasajeros','4921'),
(405,'Transporte mixto','4922'),
(406,'Transporte de carga por carretera','4923'),
(407,'Transporte por tuberías','4930'),
(408,'Transporte acuático','0050'),
(409,'Transporte marítimo y de cabotaje','501'),
(410,'Transporte de pasajeros marítimo y de cabotaje ','5011'),
(411,'Transporte de carga marítimo y de cabotaje ','5012'),
(412,'Transporte fluvial','502'),
(413,'Transporte fluvial de pasajeros','5021'),
(414,'Transporte fluvial de carga','5022'),
(415,'Transporte aéreo','0051'),
(416,'Transporte aéreo de pasajeros ','511'),
(417,'Transporte aéreo nacional de pasajeros ','5111'),
(418,'Transporte aéreo internacional de pasajeros ','5112'),
(419,'Transporte aéreo de carga ','512'),
(420,'Transporte aéreo nacional de carga ','5121'),
(421,'Transporte aéreo internacional de carga ','5122'),
(422,'Almacenamiento y actividades complementarias al transporte','0052'),
(423,'Almacenamiento y depósito','5210'),
(424,'Actividades de las estaciones, vías y servicios complementarios para el transporte','522'),
(425,'Actividades de estaciones, vías y servicios complementarios para el transporte terrestre','5221'),
(426,'Actividades de puertos y servicios complementarios para el transporte acuático','5222'),
(427,'Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo','5223'),
(428,'Manipulación de carga','5224'),
(429,'Otras actividades complementarias al transporte','5229'),
(430,'Correo y servicios de mensajería','0053'),
(431,'Actividades postales nacionales','5310'),
(432,'Actividades de mensajería','5320'),
(433,'Alojamiento','0055'),
(434,'Actividades de alojamiento de estancias cortas','551'),
(435,'Alojamiento en hoteles ','5511'),
(436,'Alojamiento en apartahoteles','5512'),
(437,'Alojamiento en centros vacacionales ','5513'),
(438,'Alojamiento rural','5514'),
(439,'Otros tipos de alojamientos para visitantes','5519'),
(440,'Actividades de zonas de camping y parques para vehículos recreacionales','5520'),
(441,'Servicio por horas ','5530'),
(442,'Otros tipos de alojamiento n.c.p.','5590'),
(443,'Actividades de servicios de comidas y bebidas','0056'),
(444,'Actividades de restaurantes, cafeterías y servicio móvil de comidas','561'),
(445,'Expendio a la mesa de comidas preparadas','5611'),
(446,'Expendio por autoservicio de comidas preparadas','5612'),
(447,'Expendio de comidas preparadas en cafeterías','5613'),
(448,'Otros tipos de expendio de comidas preparadas n.c.p.','5619'),
(449,'Actividades de catering para eventos y otros servicios de comidas','562'),
(450,'Catering para eventos','5621'),
(451,'Actividades de otros servicios de comidas','5629'),
(452,'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento','5630'),
(453,'Actividades de edición','0058'),
(454,'Edición de libros, publicaciones periódicas y otras actividades de edición','581'),
(455,'Edición de libros','5811'),
(456,'Edición de directorios y listas de correo','5812'),
(457,'Edición de periódicos, revistas y otras publicaciones periódicas','5813'),
(458,'Otros trabajos de edición','5819'),
(459,'Edición de programas de informática (software)','5820'),
(460,'Actividades cinematográficas, de video y producción de programas de televisión, grabación de sonido y edición de música','0059'),
(461,'Actividades de producción de películas cinematográficas, video y producción de programas, anuncios y comerciales de televisión','591'),
(462,'Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión','5911'),
(463,'Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión','5912'),
(464,'Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión','5913'),
(465,'Actividades de exhibición de películas cinematográficas y videos','5914'),
(466,'Actividades de grabación de sonido y edición de música','5920'),
(467,'Actividades de programación, transmisión y/o difusión','0060'),
(468,'Actividades de programación y transmisión en el servicio de radiodifusión sonora','6010'),
(469,'Actividades de programación y transmisión de televisión','6020'),
(470,'Telecomunicaciones','0061'),
(471,'Actividades de telecomunicaciones alámbricas','6110'),
(472,'Actividades de telecomunicaciones inalámbricas','6120'),
(473,'Actividades de telecomunicación satelital','6130'),
(474,'Otras actividades de telecomunicaciones','6190'),
(475,'Desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas), consultoría informática y actividades relacionadas','0062'),
(476,'Desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas), consultoría informática y actividades relacionadas','620'),
(477,'Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)','6201'),
(478,'Actividades de consultoría informática y actividades de administración de instalaciones informáticas','6202'),
(479,'Otras actividades de tecnologías de información y actividades de servicios informáticos','6209'),
(480,'Actividades de servicios de información','0063'),
(481,'Procesamiento de datos, alojamiento (hosting) y actividades relacionadas; portales web','631'),
(482,'Procesamiento de datos, alojamiento (hosting) y actividades relacionadas','6311'),
(483,'Portales web','6312'),
(484,'Otras actividades de servicio de información','639'),
(485,'Actividades de agencias de noticias','6391'),
(486,'Otras actividades de servicio de información n.c.p.','6399'),
(487,'Actividades de servicios financieros, excepto las de seguros y de pensiones','0064'),
(488,'Intermediación monetaria','641'),
(489,'Banco Central','6411'),
(490,'Bancos comerciales','6412'),
(491,'Otros tipos de intermediación monetaria','642'),
(492,'Actividades de las corporaciones financieras','6421'),
(493,'Actividades de las compañías de financiamiento','6422'),
(494,'Banca de segundo piso','6423'),
(495,'Actividades de las cooperativas financieras','6424'),
(496,'Fideicomisos, fondos (incluye fondos de cesantías) y entidades financieras similares','643'),
(497,'Fideicomisos, fondos y entidades financieras similares','6431'),
(498,'Fondos de cesantías','6432'),
(499,'Otras actividades de servicio financiero, excepto las de seguros y pensiones','649'),
(500,'Leasing financiero (arrendamiento financiero)','6491'),
(501,'Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario','6492'),
(502,'Actividades de compra de cartera o factoring','6493'),
(503,'Otras actividades de distribución de fondos','6494'),
(504,'Instituciones especiales oficiales','6495'),
(505,'Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.','6499'),
(506,'Seguros (incluso el reaseguro), seguros sociales y fondos de pensiones, excepto la seguridad social','0065'),
(507,'Seguros y capitalización','651'),
(508,'Seguros generales ','6511'),
(509,'Seguros de vida','6512'),
(510,'Reaseguros','6513'),
(511,'Capitalización','6514'),
(512,'Servicios de seguros sociales de salud y riesgos profesionales','652'),
(513,'Servicios de seguros sociales de salud','6521'),
(514,'Servicios de seguros sociales de riesgos profesionales','6522'),
(515,'Servicios de seguros sociales de pensiones','653'),
(516,'Régimen de prima media con prestación definida (RPM)','6531'),
(517,'Régimen de ahorro individual (RAI)','6532'),
(518,'Actividades auxiliares de las actividades de servicios financieros','0066'),
(519,'Actividades auxiliares de las actividades de servicios financieros, excepto las de seguros y pensiones','661'),
(520,'Administración de mercados financieros','6611'),
(521,'Corretaje de valores y de contratos de productos básicos','6612'),
(522,'Otras actividades relacionadas con el mercado de valores','6613'),
(523,'Actividades de las casas de cambio','6614'),
(524,'Actividades de los profesionales de compra y venta de divisas','6615'),
(525,'Otras actividades auxiliares de las actividades de servicios financieros n.c.p.','6619'),
(526,'Actividades de servicios auxiliares de los servicios de seguros y pensiones','662'),
(527,'Actividades de agentes y corredores de seguros','6621'),
(528,'Evaluación de riesgos y daños, y otras actividades de servicios auxiliares','6629'),
(529,'Actividades de administración de fondos','6630'),
(530,'Actividades inmobiliarias','0068'),
(531,'Actividades inmobiliarias realizadas con bienes propios o arrendados','6810'),
(532,'Actividades inmobiliarias realizadas a cambio de una retribución o por contrato','6820'),
(533,'Actividades jurídicas y de contabilidad','0069'),
(534,'Actividades jurídicas','6910'),
(535,'Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria','6920'),
(536,'Actividades de administración empresarial; actividades de consultoría de gestión','0070'),
(537,'Actividades de administración empresarial','7010'),
(538,'Actividades de consultoría de gestión','7020'),
(539,'Actividades de arquitectura e ingeniería; ensayos y análisis técnicos','0071'),
(540,'Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica','7110'),
(541,'Ensayos y análisis técnicos','7120'),
(542,'Investigación científica y desarrollo','0072'),
(543,'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería ','7210'),
(544,'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades','7220'),
(545,'Publicidad y estudios de mercado','0073'),
(546,'Publicidad','7310'),
(547,'Estudios de mercado y realización de encuestas de opinión pública','7320'),
(548,'Otras actividades profesionales, científicas y técnicas','0074'),
(549,'Actividades especializadas de diseño ','7410'),
(550,'Actividades de fotografía','7420'),
(551,'Otras actividades profesionales, científicas y técnicas n.c.p.','7490'),
(552,'Actividades veterinarias','0075'),
(553,'Actividades veterinarias','7500'),
(554,'Actividades de alquiler y arrendamiento','0077'),
(555,'Alquiler y arrendamiento de vehículos automotores','7710'),
(556,'Alquiler y arrendamiento de efectos personales y enseres domésticos','772'),
(557,'Alquiler y arrendamiento de equipo recreativo y deportivo','7721'),
(558,'Alquiler de videos y discos ','7722'),
(559,'Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.','7729'),
(560,'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.','7730'),
(561,'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor','7740'),
(562,'Actividades de empleo','0078'),
(563,'Actividades de agencias de empleo','7810'),
(564,'Actividades de agencias de empleo temporal','7820'),
(565,'Otras actividades de suministro de recurso humano','7830'),
(566,'Actividades de las agencias de viajes, operadores turísticos, servicios de reserva y actividades relacionadas','0079'),
(567,'Actividades de las agencias de viajes y operadores turísticos','791'),
(568,'Actividades de las agencias de viaje','7911'),
(569,'Actividades de operadores turísticos','7912'),
(570,'Otros servicios de reserva y actividades relacionadas','7990'),
(571,'Actividades de seguridad e investigación privada','0080'),
(572,'Actividades de seguridad privada','8010'),
(573,'Actividades de servicios de sistemas de seguridad','8020'),
(574,'Actividades de detectives e investigadores privados','8030'),
(575,'Actividades de servicios a edificios y paisajismo (jardines, zonas verdes)','0081'),
(576,'Actividades combinadas de apoyo a instalaciones','8110'),
(577,'Actividades de limpieza','812'),
(578,'Limpieza general interior de edificios','8121'),
(579,'Otras actividades de limpieza de edificios e instalaciones industriales','8129'),
(580,'Actividades de paisajismo y servicios de mantenimiento conexos','8130'),
(581,'Actividades administrativas y de apoyo de oficina y otras actividades de apoyo a las empresas','0082'),
(582,'Actividades administrativas y de apoyo de oficina','821'),
(583,'Actividades combinadas de servicios administrativos de oficina','8211'),
(584,'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina','8219'),
(585,'Actividades de centros de llamadas (Call center)','8220'),
(586,'Organización de convenciones y eventos comerciales','8230'),
(587,'Actividades de servicios de apoyo a las empresas n.c.p.','829'),
(588,'Actividades de agencias de cobranza y oficinas de calificación crediticia','8291'),
(589,'Actividades de envase y empaque','8292'),
(590,'Otras actividades de servicio de apoyo a las empresas n.c.p.','8299'),
(591,'Administración pública y defensa; planes de seguridad social de afiliación obligatoria','0084'),
(592,'Administración del Estado y aplicación de la política económica y social de la comunidad','841'),
(593,'Actividades legislativas de la administración pública','8411'),
(594,'Actividades ejecutivas de la administración pública','8412'),
(595,'Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social ','8413'),
(596,'Actividades reguladoras y facilitadoras de la actividad económica','8414'),
(597,'Actividades de los otros órganos de control','8415'),
(598,'Prestación de servicios a la comunidad en general','842'),
(599,'Relaciones exteriores ','8421'),
(600,'Actividades de defensa','8422'),
(601,'Orden público y actividades de seguridad','8423'),
(602,'Administración de justicia','8424'),
(603,'Actividades de planes de seguridad social de afiliación obligatoria','8430'),
(604,'Educación','0085'),
(605,'Educación de la primera infancia, preescolar y básica primaria','851'),
(606,'Educación de la primera infancia','8511'),
(607,'Educación preescolar','8512'),
(608,'Educación básica primaria','8513'),
(609,'Educación secundaria y de formación laboral','852'),
(610,'Educación básica secundaria ','8521'),
(611,'Educación media académica','8522'),
(612,'Educación media técnica y de formación laboral','8523'),
(613,'Establecimientos que combinan diferentes niveles de educación ','8530'),
(614,'Educación superior','854'),
(615,'Educación técnica profesional','8541'),
(616,'Educación tecnológica','8542'),
(617,'Educación de instituciones universitarias o de escuelas tecnológicas','8543'),
(618,'Educación de universidades','8544'),
(619,'Otros tipos de educación','855'),
(620,'Formación académica no formal ','8551'),
(621,'Enseñanza deportiva y recreativa','8552'),
(622,'Enseñanza cultural','8553'),
(623,'Otros tipos de educación n.c.p.','8559'),
(624,'Actividades de apoyo a la educación','8560'),
(625,'Actividades de atención de la salud humana','0086'),
(626,'Actividades de hospitales y clínicas, con internación','8610'),
(627,'Actividades de práctica médica y odontológica, sin internación ','862'),
(628,'Actividades de la práctica médica, sin internación','8621'),
(629,'Actividades de la práctica odontológica','8622'),
(630,'Otras actividades de atención relacionadas con la salud humana','869'),
(631,'Actividades de apoyo diagnóstico','8691'),
(632,'Actividades de apoyo terapéutico','8692'),
(633,'Otras actividades de atención de la salud humana','8699'),
(634,'Actividades de atención residencial medicalizada','0087'),
(635,'Actividades de atención residencial medicalizada de tipo general','8710'),
(636,'Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas','8720'),
(637,'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas','8730'),
(638,'Otras actividades de atención en instituciones con alojamiento','8790'),
(639,'Actividades de asistencia social sin alojamiento','0088'),
(640,'Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas','8810'),
(641,'Otras actividades de asistencia social sin alojamiento','8890'),
(642,'Actividades creativas, artísticas y de entretenimiento','009'),
(643,'Actividades creativas, artísticas y de entretenimiento ','900'),
(644,'Creación literaria','9001'),
(645,'Creación musical','9002'),
(646,'Creación teatral','9003'),
(647,'Creación audiovisual','9004'),
(648,'Artes plásticas y visuales','9005'),
(649,'Actividades teatrales','9006'),
(650,'Actividades de espectáculos musicales en vivo','9007'),
(651,'Otras actividades de espectáculos en vivo','9008'),
(652,'Actividades de bibliotecas, archivos, museos y otras actividades culturales','0091'),
(653,'Actividades de bibliotecas, archivos, museos y otras actividades culturales','910'),
(654,'Actividades de bibliotecas y archivos','9101'),
(655,'Actividades y funcionamiento de museos, conservación de edificios y sitios históricos','9102'),
(656,'Actividades de jardines botánicos, zoológicos y reservas naturales','9103'),
(657,'Actividades de juegos de azar y apuestas','0092'),
(658,'Actividades de juegos de azar y apuestas','9200'),
(659,'Actividades deportivas y actividades recreativas y de esparcimiento','0093'),
(660,'Actividades deportivas','931'),
(661,'Gestión de instalaciones deportivas','9311'),
(662,'Actividades de clubes deportivos','9312'),
(663,'Otras actividades deportivas','9319'),
(664,'Otras actividades recreativas y de esparcimiento','932'),
(665,'Actividades de parques de atracciones y parques temáticos','9321'),
(666,'Otras actividades recreativas y de esparcimiento n.c.p.','9329'),
(667,'Actividades de asociaciones','0094'),
(668,'Actividades de asociaciones empresariales y de empleadores, ','941'),
(669,'y asociaciones profesionales ','0163'),
(670,'Actividades de asociaciones empresariales y de empleadores','9411'),
(671,'Actividades de asociaciones profesionales','9412'),
(672,'Actividades de sindicatos de empleados','9420'),
(673,'Actividades de otras asociaciones','949'),
(674,'Actividades de asociaciones religiosas','9491'),
(675,'Actividades de asociaciones políticas','9492'),
(676,'Actividades de otras asociaciones n.c.p.','9499'),
(677,'Mantenimiento y reparación de computadores, efectos personales y enseres domésticos','0095'),
(678,'Mantenimiento y reparación de computadores y equipo de comunicaciones','951'),
(679,'Mantenimiento y reparación de computadores y de equipo periférico','9511'),
(680,'Mantenimiento y reparación de equipos de comunicación','9512'),
(681,'Mantenimiento y reparación de efectos personales y enseres domésticos','952'),
(682,'Mantenimiento y reparación de aparatos electrónicos de consumo','9521'),
(683,'Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería ','9522'),
(684,'Reparación de calzado y artículos de cuero','9523'),
(685,'Reparación de muebles y accesorios para el hogar','9524'),
(686,'Mantenimiento y reparación de otros efectos personales y enseres domésticos','9529'),
(687,'Otras actividades de servicios personales','0096'),
(688,'Otras actividades de servicios personales','960'),
(689,'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel','9601'),
(690,'Peluquería y otros tratamientos de belleza','9602'),
(691,'Pompas fúnebres y actividades relacionadas','9603'),
(692,'Otras actividades de servicios personales n.c.p.','9609'),
(693,'Actividades de los hogares individuales como empleadores de personal doméstico','0097'),
(694,'Actividades de los hogares individuales como empleadores de personal doméstico','9700'),
(695,'Actividades no diferenciadas de los hogares individuales como productores de bienes y servicios para uso propio','0098'),
(696,'Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio','9810'),
(697,'Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio','9820'),
(698,'Actividades de organizaciones y entidades extraterritoriales','0099'),
(699,'Actividades de organizaciones y entidades extraterritoriales','9900'),
(700,'Actividades creativas, artísticas y de entretenimiento','0090');

